"""Ticket document generation with persisted conversation history."""

from __future__ import annotations

import io
from html import escape
from typing import Optional

from database.crud import get_ticket_by_id, get_ticket_comments


def _export_data(ticket_id: str, *, ticket: Optional[dict] = None, comments: Optional[list[dict]] = None) -> tuple[dict, list[dict]]:
    resolved_ticket = ticket or get_ticket_by_id(ticket_id)
    if not resolved_ticket:
        raise ValueError(f"Ticket {ticket_id} not found")
    return resolved_ticket, comments if comments is not None else get_ticket_comments(ticket_id)


def generate_ticket_pdf(ticket_id: str, *, ticket: Optional[dict] = None, comments: Optional[list[dict]] = None) -> bytes:
    """Generate a PDF report containing ticket metadata and conversation."""
    ticket, comments = _export_data(ticket_id, ticket=ticket, comments=comments)

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36, title=f"TicketGenie Ticket {ticket.get('id', ticket_id)}", author="TicketGenie")
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TicketTitle", parent=styles["Heading1"], fontSize=22, leading=26, textColor=colors.HexColor("#1e293b"), spaceAfter=12)

    def cell(value: object) -> Paragraph:
        return Paragraph(escape(str(value if value is not None else "N/A")), styles["BodyText"])

    elements = [Paragraph("TicketGenie - Ticket Report", title_style), Paragraph(f"Complete record for Ticket ID: <b>{escape(str(ticket.get('id', ticket_id)))}</b>", styles["Heading3"]), Spacer(1, 16)]
    details = [
        ["Field", "Value"],
        ["Ticket ID", cell(ticket.get("id", ticket_id))],
        ["Title", cell(ticket.get("title", "N/A"))],
        ["Department", cell(ticket.get("department", "N/A"))],
        ["Category", cell(ticket.get("category", "N/A"))],
        ["Priority", cell(ticket.get("priority", "N/A"))],
        ["Status", cell(ticket.get("status", "N/A"))],
        ["Created", cell(ticket.get("createdAt") or ticket.get("date", "N/A"))],
        ["Last Updated", cell(ticket.get("updatedAt", "N/A"))],
        ["Requester ID", cell(ticket.get("requester_id", "N/A"))],
        ["Description", cell(ticket.get("description", "N/A"))],
    ]
    details_table = Table(details, colWidths=[125, 405], repeatRows=1)
    details_table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]), ("PADDING", (0, 0), (-1, -1), 7)]))
    elements.extend([details_table, Spacer(1, 22), Paragraph("Conversation History", styles["Heading2"]), Spacer(1, 8)])

    if comments:
        rows = [["Date / Time", "Sender", "Message"]]
        rows.extend([cell(c.get("createdAt", "N/A")), cell(c.get("sender_role", "Unknown")), cell(c.get("message", ""))] for c in comments)
        conversation = Table(rows, colWidths=[115, 90, 325], repeatRows=1)
        conversation.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]), ("PADDING", (0, 0), (-1, -1), 6)]))
        elements.append(conversation)
    else:
        elements.append(Paragraph("No conversation messages have been recorded.", styles["BodyText"]))

    elements.extend([Spacer(1, 24), Paragraph("<i>Generated by TicketGenie. This report contains the ticket record and public support conversation available to the requesting user.</i>", styles["Italic"])])
    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def generate_ticket_docx(ticket_id: str, *, ticket: Optional[dict] = None, comments: Optional[list[dict]] = None) -> bytes:
    """Generate a text-compatible DOCX export containing the same report data."""
    ticket, comments = _export_data(ticket_id, ticket=ticket, comments=comments)
    conversation = "\n".join(f"[{c.get('createdAt', 'N/A')}] {c.get('sender_role', 'Unknown')}: {c.get('message', '')}" for c in comments) or "No conversation messages have been recorded."
    return f"""TICKETGENIE TICKET REPORT
Ticket ID: {ticket.get('id', ticket_id)}
Title: {ticket.get('title', 'N/A')}
Department: {ticket.get('department', 'N/A')}
Category: {ticket.get('category', 'N/A')}
Priority: {ticket.get('priority', 'N/A')}
Status: {ticket.get('status', 'N/A')}
Created: {ticket.get('createdAt') or ticket.get('date', 'N/A')}
Requester ID: {ticket.get('requester_id', 'N/A')}

DESCRIPTION
{ticket.get('description', 'No description provided.')}

CONVERSATION HISTORY
{conversation}
""".encode("utf-8")
