# ==========================================================================
# Auto-Generated Azure Monitor Metric Alerts for OpenAPI Endpoints
# Generated by scripts/generate_openapi_monitoring.py
# ==========================================================================

# 1. Global High Server Error Rate Alert (5xx Errors)
resource "azurerm_monitor_metric_alert" "api_server_errors" {
  name                = "alert-ticketgenie-api-5xx-errors"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Triggers on high HTTP 5xx server errors"
  severity            = 1
  frequency           = "PT1M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 5
  }
}

# 2. Global High Latency Alert (P95 > 1000ms)
resource "azurerm_monitor_metric_alert" "api_high_latency" {
  name                = "alert-ticketgenie-api-high-latency"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Triggers when average request latency exceeds 1000ms"
  severity            = 2
  frequency           = "PT1M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/duration"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 1000
  }
}

# Alert for route: GET /tickets
resource "azurerm_monitor_metric_alert" "route_tickets_get_errors" {
  name                = "alert-api-tickets-get-failed"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Alert for failed requests on endpoint GET /tickets"
  severity            = 2
  frequency           = "PT5M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 3

    dimension {
      name     = "request/name"
      operator = "Include"
      values   = ["GET /tickets"]
    }
  }
}

# Alert for route: POST /tickets
resource "azurerm_monitor_metric_alert" "route_tickets_post_errors" {
  name                = "alert-api-tickets-post-failed"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Alert for failed requests on endpoint POST /tickets"
  severity            = 2
  frequency           = "PT5M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 3

    dimension {
      name     = "request/name"
      operator = "Include"
      values   = ["POST /tickets"]
    }
  }
}

# Alert for route: GET /tickets/{ticket_id}
resource "azurerm_monitor_metric_alert" "route_tickets_ticket_id_get_errors" {
  name                = "alert-api-tickets_ticket_id-get-failed"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Alert for failed requests on endpoint GET /tickets/{ticket_id}"
  severity            = 2
  frequency           = "PT5M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 3

    dimension {
      name     = "request/name"
      operator = "Include"
      values   = ["GET /tickets/{ticket_id}"]
    }
  }
}

# Alert for route: GET /
resource "azurerm_monitor_metric_alert" "route_root_get_errors" {
  name                = "alert-api-root-get-failed"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Alert for failed requests on endpoint GET /"
  severity            = 2
  frequency           = "PT5M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 3

    dimension {
      name     = "request/name"
      operator = "Include"
      values   = ["GET /"]
    }
  }
}

# Alert for route: GET /health
resource "azurerm_monitor_metric_alert" "route_health_get_errors" {
  name                = "alert-api-health-get-failed"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Alert for failed requests on endpoint GET /health"
  severity            = 2
  frequency           = "PT5M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 3

    dimension {
      name     = "request/name"
      operator = "Include"
      values   = ["GET /health"]
    }
  }
}
